[versions]
kotlin = "1.9.10"
# https://developer.android.com/jetpack/androidx/releases/compose-kotlin#pre-release_kotlin_compatibility
compose-compiler = "1.5.3"
room = "2.6.1"
accompanist = "0.32.0"
showkase = "1.0.0-beta15"
lifecycle = "2.6.2"
hilt = "2.51.1"

[plugins]
ksp = "com.google.devtools.ksp:1.9.10-1.0.13"
gradle-doctor = "com.osacky.doctor:0.10.0"
gradle-buildtimetracker = "com.asarkar.gradle.build-time-tracker:4.3.0"
gradle-cachefix = "org.gradle.android.cache-fix:2.8.1"
dependencyanalysis = "com.autonomousapps.dependency-analysis:1.25.0"

[libraries]
gradle-android-desugar = "com.android.tools:desugar_jdk_libs:2.0.4"
gradle-android-plugin = "com.android.tools.build:gradle:8.5.1"

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
kotlin-coroutines-test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.7.3"
kotlin-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.6"

javax-inject = "javax.inject:javax.inject:1"
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.0.0"
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }

androidx-navigation-compose = "androidx.navigation:navigation-compose:2.7.7"
androidx-activity-compose = "androidx.activity:activity-compose:1.8.0"

androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room"}

androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }

androidx-core-testing = "androidx.arch.core:core-testing:2.2.0"
androidx-test-rules = "androidx.test:rules:1.6.1"
androidx-test-runner = "androidx.test:runner:1.6.1"
androidx-junit-ext = "androidx.test.ext:junit:1.2.1"
androidx-espresso = "androidx.test.espresso:espresso-core:3.6.1"

compose-bom = "androidx.compose:compose-bom:2023.10.01"
compose-runtime = { module = "androidx.compose.runtime:runtime"}
compose-ui-ui = { module = "androidx.compose.ui:ui"}
compose-animation = { module = "androidx.compose.animation:animation"}
compose-ui-googlefonts = { module = "androidx.compose.ui:ui-text-google-fonts"}
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling"}
compose-ui-toolingpreview = { module = "androidx.compose.ui:ui-tooling-preview"}
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4"}
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest"}

compose-material3 = {module = "androidx.compose.material3:material3" }

logcat = "com.squareup.logcat:logcat:0.1"
calendarview = "com.kizitonwose.calendar:compose:2.4.0"
reorderable = "org.burnoutcrew.composereorderable:reorderable:0.9.6"

accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

bugsnag-gradle = "com.bugsnag:bugsnag-android-gradle-plugin:8.1.0"
bugsnag-runtime = "com.bugsnag:bugsnag-android-core:6.9.0"

apache-csv = "org.apache.commons:commons-csv:1.11.0"

androidx-glance-appwidget = "androidx.glance:glance-appwidget:1.1.0"

showkase-annotation = { module = "com.airbnb.android:showkase-annotation", version.ref = "showkase" }
showkase-full = { module = "com.airbnb.android:showkase", version.ref = "showkase" }
showkase-processor = { module = "com.airbnb.android:showkase-processor", version.ref = "showkase" }

junit = "junit:junit:4.13.2"
mockito-android = "org.mockito:mockito-android:5.12.0"
mockito-kotlin = "org.mockito.kotlin:mockito-kotlin:5.4.0"
turbine = "app.cash.turbine:turbine:1.0.0"

licensee = "app.cash.licensee:licensee-gradle-plugin:1.11.0"
ruler = "com.spotify.ruler:ruler-gradle-plugin:1.4.0"